version: "2.1"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

# Use the latest runtime as an image
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
